name: Build dependency cache on main branch
on:
  push:
    branches: main
    paths:
      - '.github/workflows/cache-deps.yaml'
  schedule:
    - cron: "10 0 * * *"

jobs:
  build-deps-cache-on-main:
    if: ${{ github.repository_owner == 'ai4castinghub-admin' }}
    runs-on:  ubuntu-22.04 # R not supported for ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
          use-public-rspm: true
          extra-repositories: 'https://hubverse-org.r-universe.dev'

      - name: Update R
        run: |
          sudo apt-get update

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: "devel"
          packages: |
            any::hubValidations
            any::sessioninfo
