name: Build dependency cache on main branch

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/cache-deps.yaml'
  schedule:
    - cron: "10 0 * * *"

jobs:
  build-deps-cache-on-main:
    if: ${{ github.repository_owner == 'ai4castinghub' }}
    runs-on: ubuntu-22.04

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
          use-public-rspm: true
          extra-repositories: 'https://hubverse-org.r-universe.dev'

      - name: Update APT cache
        run: sudo apt-get update

      - name: Ensure pak cache directory exists
        run: mkdir -p ~/.local/share/pak

      - name: Restore R package cache
        uses: actions/cache@v3
        with:
          path: ~/.local/share/pak
          key: ${{ runner.os }}-pak-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-pak-

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: "devel"
          packages: |
            any::hubValidations
            any::sessioninfo

      - name: Verify package installation
        run: |
          Rscript -e 'library(hubValidations); library(sessioninfo); sessioninfo::session_info()'
